#!/bin/bash

[[ -f ~/.xprofile ]] && . ~/.xprofile

# Autorun
sxhkd &
polybar -r mybar &
picom -b &
feh --bg-fill /usr/share/backgrounds/archlinux/wallpapers.jpg &

# bspwm settings
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         5
bspc config window_gap           10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Colors
bspc config normal_border_color  "#530a60"
bspc config active_border_color  "#2b1c3a"
bspc config focused_border_color "#7b0091"
bspc config presel_feedback_color "#893179"
